"""Add supabase_uid

Revision ID: 0f77a2be679a
Revises: 20260429_01
Create Date: 2026-07-24 15:25:57.130263
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f77a2be679a'
down_revision: Union[str, None] = '20260429_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_column('users', 'supabase_uid')
    # ### end Alembic commands ###
